openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-u42y.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/register.yaml

  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/reset-pwd/reset-pwd.yaml

  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email/send-reset-email.yaml

  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/login.yaml

  /auth/logout:
    delete:
      $ref: ../swagger/paths/auth/logout/logout.yaml

  /auth/refresh-session:
    patch:
      $ref: ../swagger/paths/auth/refresh-session/refresh-session.yaml

  /auth/get-oauth-url:
    get:
      $ref: ../swagger/paths/auth/get-oauth-url/get-oauth-url.yaml

  /auth/confirm-oauth:
    post:
      $ref: ../swagger/paths/auth/confirm-oauth/confirm-oauth.yaml

  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml

  /contacts/{id}:
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionId
